<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfPP8AP\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfPP8AP/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBfPP8AP.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerBfPP8AP\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerBfPP8AP\srcProdProjectContainer(array(
    'container.build_hash' => 'BfPP8AP',
    'container.build_id' => '00536c1a',
    'container.build_time' => 1539200705,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfPP8AP');
